sinkSkipList:
  - id: SinkSkipList.ThirdParties
    name: Skip Third Party Sinks
    patterns:
      - "(HTMLAnchorElement|HTMLIFrameElement|HTMLElement).*"
      - "<operator>\\..*"
      - "(?i)(string|number|array).*"
      - "JSON\\..*"
      - "(Date|Promise\\.).*"
      - "this.*"
      - "__Runtime\\..*"
      - "(?i)(Window|__ecma\\.|Document).*"
      - "src\\/.*|\\.\\.\\/.*"

  - id: SinkSkipList.BuiltInLib
    name: Skip built in language libraries
    patterns:
      - "(?i)(react\\:).*"
      - "(?i)(bunyan|winston|ramda|styled|moment|axios|gulp-|webpack).*"
