systemConfig:
  - key: maxSocketCount
    value: "4096"

  - key: RepoPropertyConfig
    value: "(?i).*(prod|production|release).*((db|data_?base|data_?source).?(host|name|url|type)|s3.?bucket)"

  - kye: propertyFileSizeLimit
    value: "10"

  - kye: "propertyFileDirCountLimit"
    value: "20"
