systemConfig:
  - key: maxSocketCount
    value: "4096"

  - key: RepoPropertyConfig
    value: "(?i).*(prod|production|release).*((db|data_?base|data_?source).?(host|name|url|type)|s3.?bucket)"

  - key: propertyFileSizeLimit
    value: "5"

  - key: propertyFileDirCountLimit
    value: "10"

  - key: maxCharLimit
    value: "1000"

  - key: dataflowElementInPathLimit
    value: "-1"

  - key: dataflowSourceSinkPairPathLimit
    value: "-1"
