systemConfig:
  - key: maxSocketCount
    value: "4096"

  - key: RepoPropertyConfig
    value: "name|config.prod.DB_HOST_NAME|config.prod.DB_LOG_NAME|dataClassification|serviceTier|isPciInScope|isSoxInScope|squad"
