exclusions:
  - id: Exclusions.Test
    name: Exclude test source code
    patterns:
      - '.*_test(s)?.*'

  - id: Exclusions.ExternalModules
    name: Exclude external modules
    patterns:
      - '(?i).*vendor(s)?/.*'
