exclusions:
  - id: Exclusions.Test
    name: Exclude test source code
    patterns:
      - "(?i)(.*(test|spec|mock)(s)?/.*)"
      - "(?i)(?:_){1,2}test(?:_){1,2}"

  - id: Exclusions.JavaScript.Packages
    name: Exclude External JavaScript Packages
    patterns:
      - ".*(node_modules|graphql).*"

  - id: Exclusions.JavaScript.MinifiedFiles
    name: Exclude External JavaScript MinifiedFiles
    patterns:
      - ".*[.]min[.]js"

  - id: Exclusions.Empty
    name: Exclude file which cannot be read
    patterns:
      - "<empty>|<unknownFullName>"

  - id: Exclusions.JQuery
    name: Exclude JQuery Folder
    patterns:
      - ".*(jquery).*([.]js).*"
