name: Vulnerability Scan
on: pull_request_target
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - run: docker build -t privado-main-oss -f Dockerfile .
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: privado-main-oss
          args: --severity-threshold=high